# Quick Watch Example Configuration
# This file shows the structure of a Quick Watch configuration
# Replace with your actual URLs, webhooks, and settings

version: "1.0"
created: 2025-01-10T10:00:00Z
updated: 2025-01-10T10:00:00Z

targets:
  my-api:
    name: "My API Service"
    url: "https://api.example.com/health"
    method: "GET"
    threshold: 30  # seconds (30s)
    check_strategy: "http"
    alerts: "console"
  
  my-website:
    name: "My Website"
    url: "https://example.com"
    method: "GET"
    threshold: 60  # seconds (60s)
    check_strategy: "http"
    alerts: "slack"

alerts:
  console:
    type: "console"
    enabled: true
    description: "Default console output"
    settings:
      style: "stylized"
      color: true
  
  slack:
    type: "slack"
    enabled: true
    description: "Slack alerts channel"
    settings:
      webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
      channel: "#alerts"
      username: "QuickWatch"
      icon_emoji: ":robot_face:"

settings:
  webhook_port: 8080
  webhook_path: "/webhook"
  check_interval: 5  # seconds (5s)
  default_threshold: 30  # seconds (30s)
  startup:
    enabled: true
    alerts:
      - console
      - slack
